import { DoctorInfo } from "@/types/dashboard";

export const doctorInfo: DoctorInfo[] = [
  {
    id: 1,
    name: "Sarah Johnson",
    speciality: "Cardiologist",
    numOfExperience: 12,
    consultationFee: 120,
    rating: 4.7,
    ratingCount: 120,
    reviewMessages: [
      {
        id: 1,
        reviewerName: "Michael Adams",
        reviewerRating: 5,
        review: "Very professional and attentive.",
        reviewDate: "2026-03-12",
      },
      {
        id: 2,
        reviewerName: "Sophie Turner",
        reviewerRating: 4,
        review: "Explained everything clearly.",
        reviewDate: "2026-02-28",
      },
    ],
    onlineAvailability: true,
    offlineAvailability: true,
    hospitalName: "Manchester Heart Centre",
  },
  {
    id: 2,
    name: "James Patel",
    speciality: "Dermatologist",
    numOfExperience: 8,
    consultationFee: 90,
    rating: 4.5,
    ratingCount: 85,
    reviewMessages: [
      {
        id: 1,
        reviewerName: "Emma Watson",
        reviewerRating: 5,
        review: "Helped clear my skin quickly.",
        reviewDate: "2026-01-15",
      },
      {
        id: 2,
        reviewerName: "Daniel Green",
        reviewerRating: 4,
        review: "Friendly and knowledgeable.",
        reviewDate: "2026-02-05",
      },
    ],
    onlineAvailability: true,
    offlineAvailability: false,
    hospitalName: "SkinCare Clinic UK",
  },
  {
    id: 3,
    name: "Emily Clarke",
    speciality: "Pediatrician",
    numOfExperience: 10,
    consultationFee: 85,
    rating: 4.8,
    ratingCount: 150,
    reviewMessages: [
      {
        id: 1,
        reviewerName: "Olivia Brown",
        reviewerRating: 5,
        review: "Great with kids, very patient.",
        reviewDate: "2026-03-01",
      },
      {
        id: 2,
        reviewerName: "James White",
        reviewerRating: 5,
        review: "Highly recommend for families.",
        reviewDate: "2026-02-18",
      },
    ],
    onlineAvailability: true,
    offlineAvailability: true,
    hospitalName: "Manchester Children’s Hospital",
  },
  {
    id: 4,
    name: "Michael Brown",
    speciality: "Orthopedic Surgeon",
    numOfExperience: 15,
    consultationFee: 150,
    rating: 4.6,
    ratingCount: 95,
    reviewMessages: [
      {
        id: 1,
        reviewerName: "Chris Evans",
        reviewerRating: 5,
        review: "Excellent surgery outcome.",
        reviewDate: "2026-01-30",
      },
      {
        id: 2,
        reviewerName: "Laura Hill",
        reviewerRating: 4,
        review: "Very experienced doctor.",
        reviewDate: "2026-02-20",
      },
    ],
    onlineAvailability: false,
    offlineAvailability: true,
    hospitalName: "Royal Orthopedic Centre",
  },
  {
    id: 5,
    name: "Aisha Khan",
    speciality: "Gynecologist",
    numOfExperience: 9,
    consultationFee: 100,
    rating: 4.7,
    ratingCount: 110,
    reviewMessages: [
      {
        id: 1,
        reviewerName: "Hannah Lee",
        reviewerRating: 5,
        review: "Made me feel very comfortable.",
        reviewDate: "2026-02-10",
      },
      {
        id: 2,
        reviewerName: "Zara Ahmed",
        reviewerRating: 4,
        review: "Professional and kind.",
        reviewDate: "2026-03-05",
      },
    ],
    onlineAvailability: true,
    offlineAvailability: true,
    hospitalName: "Women’s Health Clinic Manchester",
  },
  {
    id: 6,
    name: "Daniel Wilson",
    speciality: "Neurologist",
    numOfExperience: 14,
    consultationFee: 140,
    rating: 4.9,
    ratingCount: 130,
    reviewMessages: [
      {
        id: 1,
        reviewerName: "Robert King",
        reviewerRating: 5,
        review: "Top-notch expertise.",
        reviewDate: "2026-01-22",
      },
      {
        id: 2,
        reviewerName: "Sophia Turner",
        reviewerRating: 5,
        review: "Helped me understand my condition.",
        reviewDate: "2026-02-14",
      },
    ],
    onlineAvailability: false,
    offlineAvailability: true,
    hospitalName: "NeuroCare UK",
  },
  {
    id: 7,
    name: "Olivia Smith",
    speciality: "General Practitioner",
    numOfExperience: 6,
    consultationFee: 60,
    rating: 4.4,
    ratingCount: 70,
    reviewMessages: [
      {
        id: 1,
        reviewerName: "Daniel Scott",
        reviewerRating: 4,
        review: "Quick and helpful consultation.",
        reviewDate: "2026-03-08",
      },
      {
        id: 2,
        reviewerName: "Grace Hall",
        reviewerRating: 4,
        review: "Very approachable.",
        reviewDate: "2026-02-25",
      },
    ],
    onlineAvailability: true,
    offlineAvailability: true,
    hospitalName: "City GP Practice",
  },
  {
    id: 8,
    name: "Liam O’Connor",
    speciality: "ENT Specialist",
    numOfExperience: 11,
    consultationFee: 110,
    rating: 4.6,
    ratingCount: 90,
    reviewMessages: [
      {
        id: 1,
        reviewerName: "Ethan Clark",
        reviewerRating: 5,
        review: "Resolved my issue efficiently.",
        reviewDate: "2026-02-12",
      },
      {
        id: 2,
        reviewerName: "Mia Wilson",
        reviewerRating: 4,
        review: "Great service overall.",
        reviewDate: "2026-03-02",
      },
    ],
    onlineAvailability: true,
    offlineAvailability: false,
    hospitalName: "Manchester ENT Clinic",
  },
];